name: Deploy VuePress to GitHub Pages

on:
  push:
    branches: [master] # 只在 master 分支推送时触发

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions: # 提升 token 权限
      contents: write # 允许推送代码
      pages: write # 允许操作 GitHub Pages
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run docs:build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/.vitepress/dist
          cname: blog.xywork.top
